package com.aquar.game.database;

// Generated Nov 3, 2013 7:49:14 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1544255372285741722L;
    private Integer id;
    private String name;
    private Set games = new HashSet(0);

    public Company() {
    }

    public Company(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    public Company(Integer id, String name, Set games) {
        this.id = id;
        this.name = name;
        this.games = games;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Set getGames() {
        return this.games;
    }

    public void setGames(Set games) {
        this.games = games;
    }
    
    @Override
    public String toString() {
        return name;
    }

}
