package com.aquar.game.database;

// Generated Jan 3, 2014 2:58:47 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Game generated by hbm2java
 */
public class Game implements java.io.Serializable {

    private Integer id;
    private Company company;
    private String name;
    private Integer type;
    private Date releaseDate;

    public Game() {
    }

    public Game(String name) {
        this.name = name;
    }

    public Game(Company company, String name, Integer type, Date releaseDate) {
        this.company = company;
        this.name = name;
        this.type = type;
        this.releaseDate = releaseDate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Date getReleaseDate() {
        return this.releaseDate;
    }

    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    @Override
    public String toString() {
        // TODO Auto-generated method stub
        return name;
    }
}
