package com.aquar.game.database;

// Generated Nov 3, 2013 7:49:14 PM by Hibernate Tools 4.0.0

/**
 * Game generated by hbm2java
 */
public class Game implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 7440476923702116207L;
    private Integer id;
    private Company company;
    private String name;
    private Integer type;

    public Game() {
    }

    public Game(Integer id, Company company, Integer type) {
        this.id = id;
        this.company = company;
        this.type = type;
    }

    public Game(Integer id, Company company, String name, Integer type) {
        this.id = id;
        this.company = company;
        this.name = name;
        this.type = type;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
